from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Protocol

from webauthn import (
    generate_authentication_options,
    generate_registration_options,
    verify_authentication_response,
    verify_registration_response,
)
from webauthn.helpers import parse_authentication_credential_json
from webauthn.helpers.structs import (
    AuthenticatorSelectionCriteria,
    PublicKeyCredentialDescriptor,
    ResidentKeyRequirement,
    UserVerificationRequirement,
)

if TYPE_CHECKING:
    from webauthn.helpers.structs import (
        PublicKeyCredentialCreationOptions,
        PublicKeyCredentialRequestOptions,
    )

    from krabsvault.users import (
        ProvidesUser,
        User,
    )


@dataclass
class WebauthnCredential:
    id: bytes  # unique credential identifier, generated by the authenticator
    public_key: bytes  # public key used to verify authentication signatures
    signature_count: int  # incremented on each use, helps detect cloned authenticators
    user_id: int  # owner of this credential


@dataclass
class RelyingParty:
    id: str  # domain name (e.g. "localhost")
    name: str  # human-readable name, displayed by the authenticator
    origin: str  # full origin URL (e.g. "http://localhost:8000")


# region Protocol for Webauthn credential storage
class WebauthnCredentialStorage(Protocol):
    def get_credentials_by_user_id(
        self,
        user_id: int,
    ) -> list[WebauthnCredential]: ...
    def get_credential_by_id(
        self,
        credential_id: bytes,
    ) -> WebauthnCredential | None: ...
    def save_credential(
        self,
        credential: WebauthnCredential,
    ) -> None: ...
    def update_signature_count(
        self,
        credential_id: bytes,
        signature_count: int,
    ) -> None: ...


# endregion


class WebauthnAuthenticator:
    def __init__(
        self,
        relying_party: RelyingParty,
        user_provider: ProvidesUser,
        credential_storage: WebauthnCredentialStorage,
    ) -> None:
        self._rp = relying_party
        self._user_provider = user_provider
        self._credential_storage = credential_storage

    # region Registration
    def create_registration_options(
        self,
        user: User,
    ) -> PublicKeyCredentialCreationOptions:
        existing = self._credential_storage.get_credentials_by_user_id(
            user.id,
        )
        return generate_registration_options(
            rp_id=self._rp.id,
            rp_name=self._rp.name,
            user_name=user.username,
            user_id=user.user_handle,
            user_display_name=user.display_name,
            exclude_credentials=[
                PublicKeyCredentialDescriptor(id=c.id) for c in existing
            ],
            authenticator_selection=AuthenticatorSelectionCriteria(
                resident_key=ResidentKeyRequirement.REQUIRED,
                user_verification=UserVerificationRequirement.PREFERRED,
            ),
        )

    def verify_registration(
        self,
        credential_json: str | dict[str, Any],
        expected_challenge: bytes,
        user_id: int,
    ) -> WebauthnCredential:
        verification = verify_registration_response(
            credential=credential_json,
            expected_challenge=expected_challenge,
            expected_rp_id=self._rp.id,
            expected_origin=self._rp.origin,
        )
        credential = WebauthnCredential(
            id=verification.credential_id,
            public_key=verification.credential_public_key,
            signature_count=verification.sign_count,
            user_id=user_id,
        )
        self._credential_storage.save_credential(credential)
        return credential

    # endregion

    # region Authentication
    def create_authentication_options(
        self,
    ) -> PublicKeyCredentialRequestOptions:
        return generate_authentication_options(
            rp_id=self._rp.id,
            user_verification=UserVerificationRequirement.PREFERRED,
        )

    def verify_authentication(
        self,
        credential_json: str | dict[str, Any],
        expected_challenge: bytes,
    ) -> User:
        parsed = parse_authentication_credential_json(credential_json)

        stored = self._credential_storage.get_credential_by_id(
            parsed.raw_id,
        )
        if stored is None:
            msg = "Unknown credential"
            raise ValueError(msg)

        verification = verify_authentication_response(
            credential=parsed,
            expected_challenge=expected_challenge,
            expected_rp_id=self._rp.id,
            expected_origin=self._rp.origin,
            credential_public_key=stored.public_key,
            credential_current_sign_count=stored.signature_count,
        )

        self._credential_storage.update_signature_count(
            credential_id=stored.id,
            signature_count=verification.new_sign_count,
        )

        user = self._user_provider.get_user_by_id(stored.user_id)
        if user is None:
            msg = "User not found for credential"
            raise ValueError(msg)

        return user

    # endregion
